pipeline {
    agent any
   
    stages{
        steps("checkout:git") {
            git branch: "master", url: ""
        }

        steps("Build:Maven") { 
                    steps {
                        sh 'mvn -B -DskipTests clean package' 
                    }
                }
            }
        }
