pipeline {
    agent any
    stages {
        stage("checkout:git") {
            steps {
                git branch: "master", url: "https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("Build:Maven") {     
            steps {
                sh '$MVN -B -DskipTests clean package' 
            }
        }
        stage("Analise:Sonar"){
            steps {
                sh '$MVN sonar:sonar \
                    -Dsonar.projectKey=BecaDevops:master \
                    -Dsonar.host.url=http://localhost:9000 \
                    -Dsonar.login=(token gerado pelo sonar)'
            }    
        }
    }
}
